[package]
name = "famiq_macros"
version = "0.1.0"
edition = "2024"

[lib]
name = "famiq_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = "2.0.100"
quote = "1.0.40"
proc-macro2 = "1.0.95"
darling = "0.20.11"
